name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        version: 14.x
    - name: Test
      run: |
        npm ci
        npm test
    - name: Test GitHub API calls
      run: npm run test:ghapi
