name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        version: 16.x
    - name: Test
      run: |
        npm ci
        npm test
    - name: Test GitHub API calls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UNRELEASED_GITHUB_APP_CREDS: ${{ secrets.UNRELEASED_GITHUB_APP_CREDS }}
      run: npm run test:ghapi
